<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>Commando.Agent</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Commando.Shared\Commando.Shared.csproj" />
    <None Include="..\..\config\commando-agent.example.json"
          Link="commando-agent.example.json"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
    <None Include="..\..\config\commando-agent-linux.example.json"
          Link="commando-agent-linux.example.json"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
